linters:
    enable:
        - errcheck

linters-settings:
    errcheck:
        exclude-functions:
            # Exclude because of the defer
            - (*github.com/sevlyar/go-daemon.Context).Release
